services:
  safepet-db:
    image: postgres:16-alpine
    container_name: safepet-db
    restart: unless-stopped
    ports:
      - '${DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-safepet_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-safepet_secret}
      POSTGRES_DB: ${DB_NAME:-safepet_db}
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME:-safepet_user} -d ${DB_NAME:-safepet_db}']
      interval: 10s
      timeout: 5s
      retries: 5
